# Generated by Django 4.2.5 on 2024-01-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=30)),
                ('robot_type', models.CharField(max_length=30)),
                ('robot_slug', models.SlugField(max_length=30)),
                ('robot_icon', models.ImageField(default='', upload_to='RosWebApp/images')),
            ],
        ),
    ]
