# Generated by Django 4.2.5 on 2023-12-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RosWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
