# Generated by Django 4.2.5 on 2024-01-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RosWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='robot_type',
            field=models.CharField(choices=[('Turtlebot', 'Turtlebot'), ('UAV-Copter', 'UAV-Copter'), ('UGV-Rover', 'UGV-Rover'), ('Mobile-Robot', 'Mobile-Robot')], max_length=30),
        ),
    ]
