# Generated by Django 4.2.5 on 2023-12-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RosWebApp', '0002_robot_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='slug',
        ),
    ]
