# Generated by Django 4.2.5 on 2023-12-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RosWebApp', '0003_remove_robot_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='robot_description',
        ),
        migrations.AddField(
            model_name='robot',
            name='robot_icon',
            field=models.ImageField(default='', upload_to='robot_images/'),
        ),
    ]
