# Generated by Django 4.2.5 on 2023-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RosWebApp', '0004_remove_robot_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='robot_icon',
            field=models.ImageField(default='', upload_to='RosWebApp/images'),
        ),
    ]
