# Generated by Django 4.2.15 on 2024-08-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=30)),
                ('robot_type', models.CharField(choices=[('Turtlebot', 'Turtlebot'), ('UAV-Copter', 'UAV-Copter'), ('UGV-Rover', 'UGV-Rover'), ('Mobile-Robot', 'Mobile-Robot')], max_length=30)),
                ('robot_slug', models.SlugField(unique=True)),
                ('robot_icon', models.ImageField(default='', upload_to='cloud_robotics_app/images')),
            ],
        ),
    ]
